# File generated by the BNF Converter (bnfc 2.9.5).

from setuptools import setup, find_packages
setup(name = 'pygment-external', version = 0.1,
      packages = ['external'],
      entry_points = {'pygments.lexers':"external=external:ExternalLexer"},
      install_requires = ['pygments'])
